// Package cmd — auth.go manages ~/.mclaude/auth.json, the NATS credential
// file written by mclaude login and consumed by mclaude import.
package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// AuthCredentials are the user-level NATS credentials written by mclaude login.
// Format spec (ADR-0053, spec-cli.md):
//
//	{ "jwt": "<nats-jwt>", "nkeySeed": "<local-nkey-seed>", "userSlug": "<uslug>" }
//
// The JWT is a NATS user JWT signed by the control-plane.
// The NKeySeed is the local NKey seed generated by the CLI — never sent to the server.
// The UserSlug is included for convenience (avoids loading context.json separately).
type AuthCredentials struct {
	JWT      string `json:"jwt"`
	NKeySeed string `json:"nkeySeed"`
	UserSlug string `json:"userSlug"`
}

// DefaultAuthPath returns the path to ~/.mclaude/auth.json.
// Respects MCLAUDE_HOME for tests.
func DefaultAuthPath() string {
	return filepath.Join(mclaudeDir(), "auth.json")
}

// LoadAuth reads auth credentials from path.
// Returns an informative error if the file is missing (login required).
func LoadAuth(path string) (*AuthCredentials, error) {
	if path == "" {
		path = DefaultAuthPath()
	}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, fmt.Errorf("not logged in: run 'mclaude login' first (credentials not found at %s)", path)
	}
	if err != nil {
		return nil, fmt.Errorf("read auth file %s: %w", path, err)
	}
	var creds AuthCredentials
	if err := json.Unmarshal(data, &creds); err != nil {
		return nil, fmt.Errorf("parse auth file %s: %w", path, err)
	}
	if creds.JWT == "" {
		return nil, fmt.Errorf("auth file %s is missing jwt field: run 'mclaude login' again", path)
	}
	if creds.NKeySeed == "" {
		return nil, fmt.Errorf("auth file %s is missing nkeySeed field: run 'mclaude login' again", path)
	}
	return &creds, nil
}

// SaveAuth writes credentials to path with mode 0600 (user-readable only).
// Creates parent directories as needed.
func SaveAuth(path string, creds *AuthCredentials) error {
	if path == "" {
		path = DefaultAuthPath()
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("create auth dir: %w", err)
	}
	data, err := json.MarshalIndent(creds, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal auth credentials: %w", err)
	}
	if err := os.WriteFile(path, append(data, '\n'), 0600); err != nil {
		return fmt.Errorf("write auth file %s: %w", path, err)
	}
	return nil
}
