{{- if and .Values.minio.enabled (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mclaude-cp.fullname" . }}-minio
  namespace: {{ include "mclaude-cp.namespace" . }}
  labels:
    {{- include "mclaude-cp.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
data:
  access-key: {{ .Values.minio.rootUser | b64enc | quote }}
  secret-key: {{ .Values.minio.rootPassword | b64enc | quote }}
{{- end }}
