{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "mclaude-cp.namespace" . }}
  labels:
    {{- include "mclaude-cp.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}
