{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mclaude-cp.fullname" . }}-postgres
  namespace: {{ include "mclaude-cp.namespace" . }}
  labels:
    {{- include "mclaude-cp.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "mclaude-cp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mclaude-cp.fullname" . }}-postgres-headless
  namespace: {{ include "mclaude-cp.namespace" . }}
  labels:
    {{- include "mclaude-cp.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mclaude-cp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
{{- end }}
