{{- if .Values.controlPlane.devOAuthToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controlPlane.existingSecret }}
  namespace: {{ include "mclaude.namespace" . }}
  labels:
    {{- include "mclaude.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  dev-oauth-token: {{ .Values.controlPlane.devOAuthToken | b64enc | quote }}
{{- end }}
