{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mclaude.serviceAccountName" . }}
  namespace: {{ include "mclaude.namespace" . }}
  labels:
    {{- include "mclaude.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
